repos:
  - repo: local
    hooks:
      - id: moonlight-api-status
        name: Moonlight API Notifier
        sub_hook: Discord
        entry: bash
        args: [ oldStatus, newStatus ]
        stages: [ commit ]
        language: system

      - id: moonlight-mint-port
        name: Moonlight Game Engine - Porting
        entry: python
        language: system